modLoader="javafml"
loaderVersion="[43,)"
license="GNU Lesser General Public License v3.0"

[[mods]]
modId="artistic_additions"
version="${file.jarVersion}"
displayName="Jayla's Artistic Additions"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="logo.png"
credits="Original mod and assets by _JWX"
authors="MiteBeMana"
description='''
'''
[[dependencies.artistic_additions]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.artistic_additions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
